### ISSUE TITLE
Crash on One Plus device

### ISSUE THREAD

**Issue by navinilavarasan** [shuhart/StepView#10]
Device Info:
Android: 6.0.1
Android Build: MHC19Q
Manufacturer: OnePlus
Model: A0001
Thread: main-1

App trace:
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.shuhart.stepview.StepView.getCirclePositions(StepView.java:258)
	at com.shuhart.stepview.StepView.measureAttributes(StepView.java:242)
	at com.shuhart.stepview.StepView.onMeasure(StepView.java:191)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:18799)
	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
	at android.view.View.measure(View.java:18799)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by shuhart** [comment]
Post the code to reproduce.

**Comment by navinilavarasan** [comment]
I will try and create a sample app where I can reproduce this and drop...

**Comment by shuhart** [comment]
:thumbsup:
