### ISSUE TITLE
Crash - Attempt to read from null array

### ISSUE THREAD

**Issue by Somnium99** [shuhart/StepView#11]
it suddenly started crashing.. on "go( .... , true)" method

 ```
E/AndroidRuntime: FATAL EXCEPTION: Data Initializing Thread
                                                               
 java.lang.NullPointerException: Attempt to read from null array
 at com.shuhart.stepview.StepView.getAnimator(StepView.java:276)
 at com.shuhart.stepview.StepView.animate(StepView.java:241)
 at com.shuhart.stepview.StepView.go(StepView.java:218)
 at MyActivity$2.run(MyActivity.java:60)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by shuhart** [comment]
Post a code to reproduce.

**Comment by mohammadaminha** [comment]
I have the same Issue to
this is my code
`val list: kotlin.collections.MutableList<String> = java.util.ArrayList()
        list.add("step1")
        list.add("step2")
        list.add("step3")

        step_view.setStepsNumber(3)
        step_view.setSteps(list)`

**Comment by shuhart** [comment]
You try to combine 2 different view mode at once. Only call `step_view.setSteps(list)` if you want the circles and texts below them. Look carefully in the examples provided by readme.
