### ISSUE TITLE
Not Working inside List View with adpater.

### ISSUE THREAD

**Issue by atulgoswami21** [shuhart/StepView#28]
Hi,

Initializing in adapter like this.

 holder.stepView.getState().steps(steps)

              .selectedTextColor(ContextCompat.getColor(context, R.color.colorAccent))
              .animationType(StepView.ANIMATION_CIRCLE)
              .doneStepLineColor(ContextCompat.getColor(context, R.color.colorPrimary))
              .doneCircleColor(ContextCompat.getColor(context, R.color.colorPrimary))
              .doneTextColor(ContextCompat.getColor(context, R.color.colorPrimary))
              .doneStepMarkColor(ContextCompat.getColor(context, R.color.white))
              .selectedCircleColor(ContextCompat.getColor(context, R.color.colorAccent))
              .selectedCircleRadius(context.getResources().getDimensionPixelSize(R.dimen.dp14))
              .selectedStepNumberColor(ContextCompat.getColor(context, R.color.colorAccent))
              .animationDuration(context.getResources().getInteger(android.R.integer.config_shortAnimTime))
              .stepLineWidth(context.getResources().getDimensionPixelSize(R.dimen.dp1))
              .textSize(context.getResources().getDimensionPixelSize(R.dimen.sp10))
              .nextStepLineColor(ContextCompat.getColor(context, R.color.font_black_5))
              .nextStepLineColor(ContextCompat.getColor(context, R.color.font_black_5))
              .nextTextColor(ContextCompat.getColor(context, R.color.font_black_5))
              .stepNumberTextSize(context.getResources().getDimensionPixelSize(R.dimen.sp14))
              .commit();
      holder.stepView.done(true );
      holder.stepView.go(getPosition(tblOrderHeader.getStageId()),false);

Fatal Exception: java.lang.NullPointerException: Attempt to read from null array
       at com.shuhart.stepview.StepView.drawText(StepView.java:644)
       at com.shuhart.stepview.StepView.drawStep(StepView.java:590)
       at com.shuhart.stepview.StepView.onDraw(StepView.java:529)
       at android.view.View.draw(View.java:19192)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.widget.ListView.drawChild(ListView.java:3590)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:2662)
       at android.widget.ListView.dispatchDraw(ListView.java:3585)
       at android.view.View.draw(View.java:19195)
       at android.widget.AbsListView.draw(AbsListView.java:4334)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at com.android.internal.policy.DecorView.draw(DecorView.java:789)
       at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3105)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3019)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6499)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

and Working inside normal view perfectly.

Thanks in advance.

**Comment by shuhart** [comment]
Fixed in 1.3.2
