### ISSUE TITLE
Not able to add step list to stepview. App crashes

### ISSUE THREAD

**Issue by JibuVarghese** [shuhart/StepView#30]
<com.shuhart.stepview.StepView
            android:id="@+id/step_view"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:background="#003d5c"
            android:padding="16dp"
            app:sv_animationType="All"
            app:sv_stepPadding="4dp"
            />

Code:
final StepView stepView = findViewById(R.id.step_view);
        List<String> stepList = new ArrayList<>();
        stepList.add("Step 1");
        stepList.add("Step 2");
        stepList.add("Step 3");
        stepList.add("Step 4");
        stepList.add("Step 5");
        stepView.setSteps(stepList);

        stepView.go(1, true);
        stepView.setOnStepClickListener(new StepView.OnStepClickListener() {
            @Override
            public void onStepClick(int step) {
                Toast.makeText(DetailsActivity.this, "Step " + step, Toast.LENGTH_SHORT).show();
                stepView.done(true);
                stepView.go(step+1, true);
            }
        });

java.lang.NullPointerException: Attempt to read from null array
                      at com.shuhart.stepview.StepView.drawText(StepView.java:643)
                      at com.shuhart.stepview.StepView.drawStep(StepView.java:589)
                      at com.shuhart.stepview.StepView.onDraw(StepView.java:528)
                      at android.view.View.draw(View.java:20207)
                      at android.view.View.updateDisplayListIfDirty(View.java:19082)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.updateDisplayListIfDirty(View.java:19073)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.draw(View.java:20210)
                      at android.widget.ScrollView.draw(ScrollView.java:1739)
                      at android.view.View.updateDisplayListIfDirty(View.java:19082)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.updateDisplayListIfDirty(View.java:19073)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.updateDisplayListIfDirty(View.java:19073)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.updateDisplayListIfDirty(View.java:19073)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.updateDisplayListIfDirty(View.java:19073)
                      at android.view.View.draw(View.java:19935)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
                      at android.view.View.draw(View.java:20210)
                      at com.android.internal.policy.DecorView.draw(DecorView.java:780)
                      at android.view.View.updateDisplayListIfDirty(View.java:19082)
                      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
                      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
                      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:761)
                      at android.view.Choreographer.doFrame(Choreographer.java:696)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by JibuVarghese** [comment]
Hi, When I downgrade to 1.2.8 it works but setSteponclicklistener is not there

**Comment by JibuVarghese** [comment]
Removed scrollview and added constrainlayout. Now working fine with 1.3.1 . But Sir how to use stepview with scrollview and recyclerview.

**Comment by shuhart** [comment]
Fixed a bunch of issues related with RecyclerView in 1.3.2. Reopen if your problem still exist.
