### ISSUE TITLE
Attempt to read from null array

### ISSUE THREAD

**Issue by Supercaly** [shuhart/StepView#7]
Every time i rotate the screen this error happen

`Caused by: java.lang.NullPointerException: Attempt to read from null array
                                                                        at com.shuhart.stepview.StepView.getAnimator(StepView.java:205)
                                                                        at com.shuhart.stepview.StepView.animate(StepView.java:170)
                                                                        at com.shuhart.stepview.StepView.go(StepView.java:152)
                                                                        at com.supercaly.petify.Activities.AggiungiActivity.setStep(AggiungiActivity.java:96)
                                                                        at com.supercaly.petify.Activities.AggiungiActivity.onCreate(AggiungiActivity.java:56)
                                                                        at android.app.Activity.performCreate(Activity.java:6237)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)`

**Comment by shuhart** [comment]
Can't reproduce. Could you post the code?

**Comment by shuhart** [comment]
Reopen, if it's still relevant.

**Comment by vkrissz** [comment]
Same problem here.
It is caused when the view is added and measured without steps, than in first frames the steps are set. After this the go(x, **true**) method throws this error as `startLinesX` and `endLinesX` arrays are null.
When I add it in the viewCreated method it works correctly.

**Comment by shuhart** [comment]
Still can't get it. Are you sure you have the latest version?
